import { CURRICULUM_VERSION } from "@/lib/types";
import type { Item } from "@/lib/types";

const BASE = {
  curriculumVersion: CURRICULUM_VERSION,
  version: 1,
  calculator: "not_needed" as const,
  source: "original" as const,
  authorId: "author.mehta",
  reviewerId: "reviewer.alvarez",
  publicationState: "published" as const,
};

function mcq(partial: Omit<Item, "curriculumVersion" | "version" | "source" | "authorId" | "reviewerId" | "publicationState" | "calculator"> & Partial<Pick<Item, "calculator" | "publicationState" | "version">>): Item {
  return { ...BASE, ...partial };
}

export const DIAGNOSTIC_ITEMS: Item[] = [
  mcq({
    id: "diag-slope-line",
    unitId: "foundation",
    topicId: "f-graphs",
    objectiveId: "F.G.1",
    primaryConceptId: "c-slope-as-rate",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-slope-read",
    expectedTimeSec: 60,
    prompt:
      "A straight line on a graph of position x (metres) versus time t (seconds) passes through (0 s, 0 m) and (4 s, 8 m). What is the slope of this line?",
    stimulus: {
      kind: "position-time",
      caption: "Position versus time for a cart that travels in a straight line.",
      alt: "A straight line from the origin to 8 metres at 4 seconds.",
      points: [
        { t: 0, x: 0 },
        { t: 4, x: 8 },
      ],
      showSlope: true,
    },
    choices: [
      { id: "a", text: "8 m", distractorRationale: "This is the height of the last point, not the slope.", misconceptionTag: "mc-height-as-slope" },
      { id: "b", text: "4 s", distractorRationale: "This is the run only." },
      { id: "c", text: "2 m/s" },
      { id: "d", text: "0.5 s/m", distractorRationale: "This inverts rise and run." },
    ],
    correctChoiceId: "c",
    solution:
      "Slope is rise over run: (8 m − 0 m)/(4 s − 0 s) = 2 m/s. The vertical value 8 m is the position at 4 s, not the rate of change.",
    hints: [
      "Slope asks how steep the line is, not how high it sits.",
      "Use Δx/Δt with the two labelled points.",
      "Compute (8 − 0) / (4 − 0) and keep the units metres per second.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "diagnostic",
    accessibilityDescription: "Straight line on an x versus t graph from the origin to 8 m at 4 s.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-read-coords",
    unitId: "foundation",
    topicId: "f-graphs",
    objectiveId: "F.G.1",
    primaryConceptId: "c-slope-as-rate",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-coord",
    expectedTimeSec: 45,
    prompt: "On the graph, what is the cart’s position at t = 3 s?",
    stimulus: {
      kind: "position-time",
      caption: "A cart moving at constant velocity.",
      alt: "Straight line from 0 m at 0 s to 10 m at 5 s.",
      points: [
        { t: 0, x: 0 },
        { t: 5, x: 10 },
      ],
      highlightT: 3,
      showHeight: true,
    },
    choices: [
      { id: "a", text: "3 m", distractorRationale: "Confuses the time coordinate with position." },
      { id: "b", text: "6 m" },
      { id: "c", text: "10 m", distractorRationale: "Reads the end of the graph, not t = 3 s." },
      { id: "d", text: "5 m", distractorRationale: "Uses the total time instead of the coordinate." },
    ],
    correctChoiceId: "b",
    solution: "The line has slope 2 m/s, so x = 2t. At 3 s the position is 6 m. You can also read the vertical coordinate at t = 3 s.",
    hints: [
      "Find t = 3 s on the horizontal axis, then read the matching height.",
      "The line is x = 2t if it goes from 0 to 10 m in 5 s.",
      "2 m/s × 3 s = 6 m.",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Straight x-t line; a marker at 3 seconds.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-velocity-units",
    unitId: "foundation",
    topicId: "f-algebra",
    objectiveId: "F.A.1",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-units",
    expectedTimeSec: 40,
    prompt: "Average velocity is change in position divided by change in time. Which unit is correct for velocity?",
    choices: [
      { id: "a", text: "m" },
      { id: "b", text: "s" },
      { id: "c", text: "m/s" },
      { id: "d", text: "m·s" },
    ],
    correctChoiceId: "c",
    solution: "Δx has units metres and Δt has units seconds, so Δx/Δt has units m/s.",
    hints: [
      "Write the definition with units in place of the symbols.",
      "Division of metres by seconds produces metres per second.",
      "m/s is the SI unit of velocity in this course.",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Multiple choice about units of velocity.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-displacement-distance",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.1",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-displacement",
    expectedTimeSec: 50,
    prompt:
      "A student walks 4 m east, then 4 m west, returning to the start. Which statement is true?",
    choices: [
      { id: "a", text: "Displacement is 8 m east and distance is 0." },
      { id: "b", text: "Displacement is 0 and distance is 8 m." },
      { id: "c", text: "Displacement and distance are both 8 m." },
      { id: "d", text: "Displacement and distance are both 0." },
    ],
    correctChoiceId: "b",
    solution:
      "Distance adds path length: 4 m + 4 m = 8 m. Displacement is the change in position from start to finish, which is 0.",
    hints: [
      "Distance is how far you travelled. Displacement is where you ended relative to where you started.",
      "The student finishes at the starting mark.",
      "Path length is 8 m; change in position is 0.",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Out-and-back walk of 4 metres each way.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-sign-velocity",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-sign",
    expectedTimeSec: 50,
    prompt:
      "The x-axis points to the right. A cart’s position decreases as time increases. What is the sign of the cart’s velocity?",
    choices: [
      { id: "a", text: "Positive, because the cart is moving." },
      { id: "b", text: "Negative, because position is decreasing with time." },
      { id: "c", text: "Zero, because nothing in the sentence mentions speed." },
      { id: "d", text: "Positive, because time always increases." },
    ],
    correctChoiceId: "b",
    solution:
      "v = Δx/Δt. Time increases (Δt > 0) while position decreases (Δx < 0), so velocity is negative — motion toward smaller x.",
    hints: [
      "Velocity takes the sign of Δx when time is increasing.",
      "“Position decreases” means Δx is negative.",
      "Negative velocity means motion in the negative-x direction, not “slowing down.”",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Qualitative sign of velocity when position decreases.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-algebra-solve",
    unitId: "foundation",
    topicId: "f-algebra",
    objectiveId: "F.A.2",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "foundation",
    familyId: "fam-algebra",
    calculator: "allowed",
    expectedTimeSec: 60,
    prompt:
      "A ball is thrown upward with v₀ = 12 m/s. Take upward as positive and g = 10 m/s² downward, so a = −10 m/s². Using v = v₀ + at, how many seconds elapse before the velocity is 0?",
    numerical: {
      value: 1.2,
      unit: "s",
      tolerance: 0.05,
      acceptedUnits: ["s", "sec", "seconds"],
    },
    solution: "0 = 12 + (−10)t → 10t = 12 → t = 1.2 s.",
    hints: [
      "Set v = 0 at the highest point and solve for t.",
      "Substitute: 0 = 12 − 10t.",
      "t = 12/10 = 1.2 s.",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Solve v = v0 + at for the time when v = 0.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-independent-variable",
    unitId: "foundation",
    topicId: "f-measure",
    objectiveId: "F.M.1",
    primaryConceptId: "c-slope-as-rate",
    secondaryConceptIds: [],
    sciencePractice: "experimental",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-iv",
    expectedTimeSec: 45,
    prompt:
      "A student measures a cart’s position at several clock readings. In a graph of position versus time, which quantity is the independent variable?",
    choices: [
      { id: "a", text: "Position, because it is what we care about." },
      { id: "b", text: "Time, because the student chooses when to record each reading." },
      { id: "c", text: "Velocity, because it is the slope." },
      { id: "d", text: "The cart’s mass." },
    ],
    correctChoiceId: "b",
    solution:
      "The independent variable is the one the experimenter sets or uses as the controlled axis — here, the clock reading. Position is the measured dependent quantity. Time belongs on the horizontal axis.",
    hints: [
      "Independent variables usually sit on the horizontal axis in this course.",
      "The student decides the times at which to look at the ruler.",
      "Time is independent; position depends on the chosen time.",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Identify the independent variable in a motion experiment.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-xt-constant-v",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: ["c-slope-as-rate"],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-xt-shape",
    expectedTimeSec: 50,
    prompt: "Which description matches a straight, sloped line on a position-time graph?",
    choices: [
      { id: "a", text: "The object is at rest." },
      { id: "b", text: "The object moves at constant velocity." },
      { id: "c", text: "The object is speeding up." },
      { id: "d", text: "The object is slowing down." },
    ],
    correctChoiceId: "b",
    solution:
      "A straight x-t graph has constant slope, and slope is velocity, so velocity is constant. Rest would be a horizontal line. Speeding up or slowing down would curve the graph (changing slope).",
    hints: [
      "Constant slope means a constant rate of change of position.",
      "Velocity is that rate of change.",
      "Curvature, not a straight tilt, signals changing velocity.",
    ],
    misconceptionTags: [],
    exposurePool: "diagnostic",
    accessibilityDescription: "Interpret a straight sloped x-t graph.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-height-vs-slope",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: ["c-slope-as-rate"],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-height-slope",
    expectedTimeSec: 70,
    prompt:
      "At t = 2 s, cart A is at x = 8 m on a shallow line. Cart B is at x = 3 m on a much steeper line. Which cart has the greater speed at t = 2 s?",
    stimulus: {
      kind: "dual-xt",
      caption: "Two carts plotted on the same axes. A is higher at 2 s; B is steeper.",
      alt: "Cart A: shallow line through 8 m at 2 s. Cart B: steep line through 3 m at 2 s.",
      series: [
        {
          label: "A",
          points: [
            { t: 0, x: 6 },
            { t: 4, x: 10 },
          ],
        },
        {
          label: "B",
          points: [
            { t: 0, x: 0 },
            { t: 4, x: 6 },
          ],
        },
      ],
      highlightT: 2,
    },
    choices: [
      {
        id: "a",
        text: "Cart A, because it is higher on the graph.",
        distractorRationale: "Treats graph height as speed.",
        misconceptionTag: "mc-height-as-slope",
      },
      { id: "b", text: "Cart B, because its graph is steeper." },
      { id: "c", text: "They have the same speed because the time is the same." },
      { id: "d", text: "Neither has a speed; speed cannot be read from an x-t graph." },
    ],
    correctChoiceId: "b",
    solution:
      "Speed is the magnitude of the slope of x versus t. B’s line is steeper, so B is faster at that instant even though A has a larger position. Height is where the cart is, not how fast it is moving.",
    hints: [
      "Speed on an x-t graph is about steepness, not height.",
      "Compare the two slopes at t = 2 s.",
      "A sits higher (larger position) but B’s line rises faster.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "diagnostic",
    accessibilityDescription: "Two x-t lines; A higher, B steeper at 2 seconds.",
    allowNotYetLearned: true,
  }),
  mcq({
    id: "diag-turning-point",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-turning",
    expectedTimeSec: 70,
    prompt:
      "A ball is thrown straight up. Take upward as positive. At the highest point, which pair is correct?",
    choices: [
      {
        id: "a",
        text: "v = 0 and a = 0, because the ball stops.",
        distractorRationale: "Confuses stopping with zero acceleration.",
        misconceptionTag: "mc-stop-means-a-zero",
      },
      { id: "b", text: "v = 0 and a is downward (negative)." },
      { id: "c", text: "v is upward and a = 0." },
      { id: "d", text: "v is downward and a is upward." },
    ],
    correctChoiceId: "b",
    solution:
      "At the top the ball’s velocity is instantaneously zero as it changes from up to down. Gravity still acts, so acceleration remains downward. Stopping does not switch gravity off.",
    hints: [
      "Ask what interaction is still present at the top.",
      "Velocity can pass through zero while still changing.",
      "v = 0 at the peak; a stays g downward.",
    ],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "diagnostic",
    accessibilityDescription: "Ball thrown vertically; ask about v and a at the peak.",
    allowNotYetLearned: true,
  }),
];
