import { CURRICULUM_VERSION } from "@/lib/types";
import type { Item } from "@/lib/types";

const BASE = {
  curriculumVersion: CURRICULUM_VERSION,
  version: 1,
  calculator: "not_needed" as const,
  source: "original" as const,
  authorId: "author.mehta",
  reviewerId: "reviewer.alvarez",
  publicationState: "published" as const,
};

function item(partial: Item): Item {
  return { ...BASE, ...partial };
}

export const LESSON_ITEMS: Item[] = [
  item({
    ...BASE,
    id: "l1-prereq-slope",
    unitId: "foundation",
    topicId: "f-graphs",
    objectiveId: "F.G.1",
    primaryConceptId: "c-slope-as-rate",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "foundation",
    familyId: "fam-slope-read",
    calculator: "allowed",
    expectedTimeSec: 50,
    prompt:
      "A line on an x-t graph goes from (1.0 s, 2.0 m) to (5.0 s, 10.0 m). What is the slope? Include the unit.",
    numerical: {
      value: 2,
      unit: "m/s",
      tolerance: 0.05,
      acceptedUnits: ["m/s", "m s^-1", "m·s^-1"],
    },
    solution: "Slope = (10.0 − 2.0) m / (5.0 − 1.0) s = 8/4 = 2.0 m/s.",
    hints: [
      "Slope is Δx divided by Δt, not the larger x value.",
      "Δx = 8 m and Δt = 4 s.",
      "8 m / 4 s = 2 m/s.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Compute slope between two points on an x-t graph.",
  }),
  item({
    ...BASE,
    id: "l1-predict-straight",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-xt-shape",
    expectedTimeSec: 45,
    prompt:
      "Before reading the explanation: a cart’s position-time graph is a straight line that slopes up. Predict the cart’s motion.",
    stimulus: {
      kind: "position-time",
      caption: "Prediction graph: a straight line with constant positive slope.",
      alt: "Straight increasing x-t line.",
      points: [
        { t: 0, x: 1 },
        { t: 5, x: 6 },
      ],
    },
    choices: [
      { id: "a", text: "The cart is speeding up because the line goes up." },
      { id: "b", text: "The cart moves at constant velocity in the positive direction." },
      { id: "c", text: "The cart is at rest at a large position." },
      { id: "d", text: "The cart is slowing down because the line will eventually flatten." },
    ],
    correctChoiceId: "b",
    solution:
      "A straight x-t graph has constant slope, so constant velocity. “Going up” means position increases, not that speed increases.",
    hints: [
      "Separate “the line is high” from “the line is getting steeper.”",
      "Constant slope means constant velocity.",
      "A straight positive slope is uniform motion in +x.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Predict motion from a straight rising x-t graph.",
  }),
  item({
    ...BASE,
    id: "l1-partial-slope",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: ["c-slope-as-rate"],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "standard",
    familyId: "fam-slope-read",
    calculator: "allowed",
    expectedTimeSec: 70,
    prompt:
      "A cart’s x-t graph is a straight line through (0.0 s, 1.0 m) and (4.0 s, 9.0 m). The system is the cart. The principle is v = Δx/Δt. Assumptions: motion is 1D; the line is straight so v is constant. What is the cart’s velocity? Include the unit.",
    stimulus: {
      kind: "position-time",
      caption: "Partially worked example. Two points are marked.",
      alt: "Straight line from 1 m at 0 s to 9 m at 4 s.",
      points: [
        { t: 0, x: 1 },
        { t: 4, x: 9 },
      ],
      showSlope: true,
    },
    numerical: {
      value: 2,
      unit: "m/s",
      tolerance: 0.05,
      acceptedUnits: ["m/s", "m s^-1"],
    },
    solution: "v = (9.0 − 1.0) m / (4.0 − 0.0) s = 2.0 m/s in the +x direction.",
    hints: [
      "Use the two given points; do not use the intercept 1 m as the answer.",
      "Δx = 8 m, Δt = 4 s.",
      "8/4 = 2 m/s.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Finish a worked slope calculation.",
  }),
  item({
    ...BASE,
    id: "l1-independent",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-height-slope",
    expectedTimeSec: 70,
    prompt:
      "A walker starts at x = 12 m and walks toward the origin at constant speed. Which x-t graph matches this motion?",
    stimulus: {
      kind: "dual-xt",
      caption: "Two candidate graphs.",
      alt: "Graph P starts high and slopes down. Graph Q starts at the origin and slopes up steeply.",
      series: [
        {
          label: "P",
          points: [
            { t: 0, x: 12 },
            { t: 6, x: 0 },
          ],
        },
        {
          label: "Q",
          points: [
            { t: 0, x: 0 },
            { t: 6, x: 12 },
          ],
        },
      ],
    },
    choices: [
      { id: "a", text: "Graph P: it starts at 12 m and the slope is negative." },
      { id: "b", text: "Graph Q: it is higher at later times, so the walker is “going somewhere.”" },
      { id: "c", text: "Neither, because a walker cannot have a straight graph." },
      { id: "d", text: "Both, because both graphs have the same steepness." },
    ],
    correctChoiceId: "a",
    solution:
      "Starting position is the intercept: 12 m. Walking toward the origin means x decreases, so the slope is negative. Graph P matches both. Graph Q starts at 0 and moves to larger x.",
    hints: [
      "Match the starting position first, then the direction.",
      "Toward the origin from +12 m means x is decreasing.",
      "Negative slope on x-t is motion toward smaller x.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Choose which graph matches walking from 12 m toward the origin.",
  }),
  item({
    ...BASE,
    id: "l1-representation",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "explanation",
    difficulty: "standard",
    familyId: "fam-explain-slope",
    expectedTimeSec: 120,
    prompt:
      "In one or two sentences, explain how you can tell from an x-t graph whether a cart is moving quickly or slowly at a chosen instant. Mention what you would not use.",
    explanationRubric: [
      {
        id: "r1",
        points: 1,
        criterion: "States that velocity or speed comes from the slope (or steepness) at that time.",
        evidenceHint: "Look for “slope,” “steep,” or “Δx/Δt.”",
      },
      {
        id: "r2",
        points: 1,
        criterion: "Explicitly rejects using only the height or the position value as speed.",
        evidenceHint: "Look for a statement that position/height is not speed.",
      },
    ],
    solution:
      "Speed at an instant is the magnitude of the slope of x versus t at that time (the tangent if the graph is curved). The height of the graph is the position, so a large x does not mean a large speed.",
    hints: [
      "Name the graph feature that is a rate.",
      "Contrast slope with the vertical coordinate.",
      "Write: slope gives v; height gives x.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Short written explanation of slope versus height.",
  }),
  item({
    ...BASE,
    id: "l1-exit",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-xt-shape",
    expectedTimeSec: 55,
    prompt:
      "A cart’s x-t graph is a curve that starts steep and becomes flatter, always with positive slope. Which statement is correct?",
    stimulus: {
      kind: "position-time",
      caption: "A concave-down x-t graph that remains increasing.",
      alt: "Position increases while the slope becomes less steep.",
      points: [
        { t: 0, x: 0 },
        { t: 1, x: 3.5 },
        { t: 2, x: 6 },
        { t: 3, x: 7.5 },
        { t: 4, x: 8.2 },
        { t: 5, x: 8.6 },
      ],
    },
    choices: [
      { id: "a", text: "The cart moves in +x and is slowing down." },
      { id: "b", text: "The cart is at rest because the graph will flatten." },
      { id: "c", text: "The cart speeds up because position is still increasing." },
      { id: "d", text: "The cart moves in −x because the curve bends down." },
    ],
    correctChoiceId: "a",
    solution:
      "Positive slope means velocity is still in +x. Decreasing steepness means the magnitude of velocity is decreasing — the cart is slowing down while still moving forward.",
    hints: [
      "Sign of slope → direction. Change of slope → speeding up or slowing down.",
      "The slope stays positive, so the cart does not reverse.",
      "Flatter means smaller speed.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Interpret a flattening but still rising x-t curve.",
  }),
  item({
    ...BASE,
    id: "l2-prereq-slope-v",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-xt-shape",
    expectedTimeSec: 40,
    prompt: "On a velocity-time graph, what does a horizontal line at v = 4 m/s represent?",
    choices: [
      { id: "a", text: "The object is at x = 4 m." },
      { id: "b", text: "The object moves at constant velocity 4 m/s." },
      { id: "c", text: "The object is stopped." },
      { id: "d", text: "The acceleration is 4 m/s²." },
    ],
    correctChoiceId: "b",
    solution:
      "A v-t graph plots velocity. A horizontal line means velocity is not changing, so acceleration is zero and motion is uniform at 4 m/s. Height here is velocity, not position.",
    hints: [
      "Read the axis labels before interpreting height.",
      "Horizontal on v-t means constant v.",
      "4 m/s is the velocity value, not an acceleration.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Interpret a horizontal v-t line.",
  }),
  item({
    ...BASE,
    id: "l2-predict-peak",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-turning",
    expectedTimeSec: 50,
    prompt:
      "A ball is thrown straight up. Before the explanation: at the highest point, what do you predict for instantaneous velocity and acceleration? Upward is positive.",
    stimulus: {
      kind: "strobe",
      caption: "Equal-time strobe of a ball thrown up and falling back.",
      alt: "Dots crowded near the top, spaced farther apart near the ground.",
      strobe: [
        { y: 0.4, label: "0" },
        { y: 1.4, label: "1" },
        { y: 2.2, label: "2" },
        { y: 2.7, label: "3" },
        { y: 2.9, label: "4 top" },
        { y: 2.7, label: "5" },
        { y: 2.2, label: "6" },
        { y: 1.4, label: "7" },
        { y: 0.4, label: "8" },
      ],
    },
    choices: [
      { id: "a", text: "v = 0 and a = 0." },
      { id: "b", text: "v = 0 and a is negative." },
      { id: "c", text: "v is positive and a is negative." },
      { id: "d", text: "v is negative and a = 0." },
    ],
    correctChoiceId: "b",
    solution:
      "The ball’s velocity changes from positive to negative, so it is instantaneously zero at the top. Gravity still acts downward, so a remains negative.",
    hints: [
      "What force is present at the top?",
      "Can velocity pass through zero without acceleration being zero?",
      "v = 0; a = −g.",
    ],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "lesson",
    accessibilityDescription: "Predict v and a at the top of a toss.",
  }),
  item({
    ...BASE,
    id: "l2-partial",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "standard",
    familyId: "fam-algebra",
    calculator: "allowed",
    expectedTimeSec: 80,
    prompt:
      "System: the ball. Principle: a is constant at −10 m/s² while in the air. v₀ = +15 m/s. Finish the calculation: at the highest point v = 0 = 15 + (−10)t. What is t in seconds?",
    numerical: {
      value: 1.5,
      unit: "s",
      tolerance: 0.05,
      acceptedUnits: ["s", "sec"],
    },
    solution: "10t = 15, so t = 1.5 s after release.",
    hints: [
      "You only need to solve the displayed equation.",
      "Move 15 to the other side.",
      "t = 1.5 s.",
    ],
    misconceptionTags: [],
    exposurePool: "lesson",
    accessibilityDescription: "Solve for time to the peak.",
  }),
  item({
    ...BASE,
    id: "l2-independent",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "transfer",
    familyId: "fam-turning-transfer",
    expectedTimeSec: 80,
    prompt:
      "A cart on a track rolls up a slight incline, momentarily stops, and rolls back. Which statement is true at the highest point?",
    choices: [
      { id: "a", text: "Velocity and acceleration are both zero because the cart stops." },
      { id: "b", text: "Velocity is zero; acceleration is down the incline (nonzero)." },
      { id: "c", text: "Velocity is down the incline; acceleration is zero." },
      { id: "d", text: "Both are nonzero and point up the incline." },
    ],
    correctChoiceId: "b",
    solution:
      "The cart’s velocity changes from up-incline to down-incline, so it is instantaneously zero at the turn. The net force (component of gravity) still points down the incline, so acceleration is not zero. A new context, same principle as the tossed ball.",
    hints: [
      "This is the tossed-ball idea on a track.",
      "Stopping for an instant is not the same as remaining at rest with no net force.",
      "v = 0; a down the slope.",
    ],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "lesson",
    accessibilityDescription: "Transfer turning-point reasoning to a cart on an incline.",
  }),
  item({
    ...BASE,
    id: "l2-representation",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: ["c-xt-velocity"],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-vt-turn",
    expectedTimeSec: 60,
    prompt:
      "Which v-t graph matches a ball thrown straight up and caught at the same height? Upward is positive.",
    stimulus: {
      kind: "velocity-time",
      caption: "A straight line from positive v, through zero, to negative v.",
      alt: "v starts positive, decreases linearly, crosses zero, becomes negative.",
      points: [
        { t: 0, v: 12 },
        { t: 1.2, v: 0 },
        { t: 2.4, v: -12 },
      ],
      highlightT: 1.2,
    },
    choices: [
      { id: "a", text: "The graph shown: v decreases through zero at a constant rate." },
      { id: "b", text: "A graph that sits at v = 0 for a stretch of time at the top." },
      { id: "c", text: "A graph that jumps discontinuously from +v to −v." },
      { id: "d", text: "A horizontal line at v = 0 the whole time." },
    ],
    correctChoiceId: "a",
    solution:
      "Constant downward acceleration means a straight v-t graph with negative slope. Velocity is zero at one instant, not for a duration. The ball does not stay at the top.",
    hints: [
      "Constant a means a straight v-t graph.",
      "Zero velocity for a duration would mean it hovered.",
      "The line crosses the time axis once.",
    ],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "lesson",
    accessibilityDescription: "Match a toss to a v-t graph that crosses zero.",
  }),
  item({
    ...BASE,
    id: "l2-exit",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "explanation",
    difficulty: "standard",
    familyId: "fam-explain-turn",
    expectedTimeSec: 120,
    prompt:
      "A classmate says “the ball stops at the top, so acceleration is zero there.” Write a one-sentence correction in your own words, then name the interaction that is still present.",
    explanationRubric: [
      {
        id: "r1",
        points: 1,
        criterion: "States that zero velocity does not imply zero acceleration / velocity is still changing.",
        evidenceHint: "Correction of the stop-means-a-zero idea.",
      },
      {
        id: "r2",
        points: 1,
        criterion: "Names gravity (or the Earth-ball gravitational interaction) as still present.",
        evidenceHint: "Mentions gravity or Earth.",
      },
    ],
    solution:
      "Velocity can be instantaneously zero while still changing, so acceleration need not vanish. Gravity still acts at the top.",
    hints: [
      "Separate the value of v from the rate of change of v.",
      "What force did not switch off?",
      "Gravity still pulls downward.",
    ],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "lesson",
    accessibilityDescription: "Correct the stop-means-zero-acceleration claim.",
  }),
  item({
    ...BASE,
    id: "l3-prereq-slope",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: ["c-slope-as-rate"],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "foundation",
    familyId: "fam-slope-read",
    calculator: "allowed",
    expectedTimeSec: 50,
    prompt:
      "A straight x-t segment runs from (0.0 s, 2.0 m) to (4.0 s, 10.0 m). What is the slope? Include the unit.",
    numerical: {
      value: 2,
      unit: "m/s",
      tolerance: 0.05,
      acceptedUnits: ["m/s", "m s^-1", "m·s^-1"],
    },
    solution: "Slope = (10.0 − 2.0) m / (4.0 − 0.0) s = 8/4 = 2.0 m/s.",
    hints: [
      "Slope is Δx/Δt, not the later height.",
      "Δx = 8 m and Δt = 4 s.",
      "8 m / 4 s = 2 m/s.",
    ],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Compute slope on a straight x-t segment before the flattening lesson.",
  }),
  item({
    ...BASE,
    id: "l3-predict-flatten",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-flattening-xt",
    secondaryConceptIds: ["c-xt-velocity"],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-flatten-xt",
    expectedTimeSec: 50,
    prompt:
      "Before the explanation: a cart’s x-t graph still rises but gets shallower. The track is straight. Predict the motion.",
    stimulus: {
      kind: "position-time",
      caption: "Prediction graph: x increases; the curve flattens.",
      alt: "Rising x-t curve that becomes shallower.",
      points: [
        { t: 0, x: 0 },
        { t: 1, x: 3.2 },
        { t: 2, x: 5.6 },
        { t: 3, x: 7.2 },
        { t: 4, x: 8.2 },
        { t: 5, x: 8.7 },
      ],
    },
    choices: [
      { id: "a", text: "The cart is going over a hill and will roll down the other side." },
      { id: "b", text: "The cart moves in +x and is slowing down." },
      { id: "c", text: "The cart is at rest because the graph is flattening." },
      { id: "d", text: "The cart is speeding up because position is still increasing." },
    ],
    correctChoiceId: "b",
    solution:
      "A still-rising curve has positive slope, so v is still toward +x. Getting shallower means |v| is falling. The graph is not a photograph of a hill.",
    hints: [
      "Rising x means the object is still moving toward +x.",
      "Shallower slope means smaller |v|.",
      "x-t is not a map of the track.",
    ],
    misconceptionTags: ["mc-graph-as-path"],
    exposurePool: "lesson",
    accessibilityDescription: "Predict motion from a flattening rising x-t graph.",
  }),
  item({
    ...BASE,
    id: "l3-partial-slopes",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-flattening-xt",
    secondaryConceptIds: ["c-xt-velocity"],
    sciencePractice: "mathematical",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-flatten-xt",
    expectedTimeSec: 70,
    prompt:
      "A cart’s x-t graph passes through (0.0 s, 1.0 m), (2.0 s, 7.0 m), and (5.0 s, 8.5 m). Compare the two average velocities. Did the cart reverse?",
    stimulus: {
      kind: "position-time",
      caption: "Three marked points on a flattening x-t curve.",
      alt: "Points at 1 m, 7 m, and 8.5 m.",
      points: [
        { t: 0, x: 1 },
        { t: 2, x: 7 },
        { t: 5, x: 8.5 },
      ],
      showSlope: true,
    },
    choices: [
      { id: "a", text: "Early average v = 3.0 m/s; late average v = 0.50 m/s; both +x, so no reverse." },
      { id: "b", text: "The cart reversed because the graph looks like a hill." },
      { id: "c", text: "Both intervals have the same velocity because position kept increasing." },
      { id: "d", text: "Late velocity is 8.5 m because that is the later height." },
    ],
    correctChoiceId: "a",
    solution:
      "(7.0 − 1.0) m / 2.0 s = 3.0 m/s. Then (8.5 − 7.0) m / 3.0 s = 0.50 m/s. Both positive, so the cart did not reverse. It slowed down.",
    hints: [
      "Average v on an interval is Δx/Δt for that interval.",
      "Sign of Δx is the direction.",
      "3.0 m/s then 0.50 m/s, both +x.",
    ],
    misconceptionTags: ["mc-graph-as-path", "mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Compare two average velocities on a flattening x-t graph.",
  }),
  item({
    ...BASE,
    id: "l3-independent",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-flattening-xt",
    secondaryConceptIds: ["c-xt-velocity"],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "transfer",
    familyId: "fam-flatten-xt",
    expectedTimeSec: 70,
    prompt:
      "A city bus on a straight avenue has an x-t graph that still rises but gets flatter from t = 8 s to t = 14 s. Which statement is true?",
    choices: [
      { id: "a", text: "The avenue must have a hill; the graph is a picture of the road." },
      { id: "b", text: "The bus is still moving forward and slowing down." },
      { id: "c", text: "The bus has stopped, because flattening always means rest." },
      { id: "d", text: "The bus is speeding up, because x is larger at 14 s than at 8 s." },
    ],
    correctChoiceId: "b",
    solution:
      "New context, same rule. Rising x-t means +x motion. Flattening means |v| is falling. A larger later position is not larger speed.",
    hints: [
      "This is the cart idea on a bus.",
      "Larger x is not larger v.",
      "Still rising and getting shallower: +x, slowing.",
    ],
    misconceptionTags: ["mc-graph-as-path", "mc-height-as-slope"],
    exposurePool: "lesson",
    accessibilityDescription: "Transfer flattening-graph reading to a bus.",
  }),
  item({
    ...BASE,
    id: "l3-representation",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-flattening-xt",
    secondaryConceptIds: ["c-xt-velocity"],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-flatten-xt",
    expectedTimeSec: 55,
    prompt:
      "Which sentence is the graph rule for a curve that still rises and gets shallower?",
    choices: [
      { id: "a", text: "The object is going over a hill; the graph is a photograph of the path." },
      { id: "b", text: "Velocity is still positive and its magnitude is decreasing." },
      { id: "c", text: "Velocity is negative because the graph is bending down." },
      { id: "d", text: "Acceleration must be zero because the object will stop soon." },
    ],
    correctChoiceId: "b",
    solution:
      "Positive slope that is getting smaller is +v with decreasing |v|. The bend is not a direction change until the slope itself changes sign.",
    hints: [
      "Slope sign is direction.",
      "Changing |slope| is speeding up or slowing down.",
      "A hill in the picture is not a hill on the floor.",
    ],
    misconceptionTags: ["mc-graph-as-path"],
    exposurePool: "lesson",
    accessibilityDescription: "State the flattening x-t rule in words.",
  }),
  item({
    ...BASE,
    id: "l3-exit",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-flattening-xt",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "explanation",
    difficulty: "standard",
    familyId: "fam-explain-flatten",
    expectedTimeSec: 120,
    prompt:
      "A classmate says “the graph looks like a hill, so the cart went over a hill.” Write a one-sentence correction. Then name the quantity the slope of this graph reports.",
    explanationRubric: [
      {
        id: "r1",
        points: 1,
        criterion: "States that an x-t graph is not a photograph/map of the track or that flattening is not a hill.",
        evidenceHint: "not a picture / not a hill / not a path in space",
      },
      {
        id: "r2",
        points: 1,
        criterion: "Names slope as velocity (or Δx/Δt), and slowing down as decreasing |v|.",
        evidenceHint: "slope / velocity",
      },
    ],
    solution:
      "The graph is position versus time, not a picture of the rails. Slope is velocity; a still-rising but shallower curve is slowing down in +x.",
    hints: [
      "What are the axes?",
      "What does a shallower slope mean?",
      "Velocity, not a hill.",
    ],
    misconceptionTags: ["mc-graph-as-path"],
    exposurePool: "lesson",
    accessibilityDescription: "Correct the graph-as-photograph claim.",
  }),
];
