import { CURRICULUM_VERSION } from "@/lib/types";
import type { Item } from "@/lib/types";

const BASE = {
  curriculumVersion: CURRICULUM_VERSION,
  version: 1,
  calculator: "not_needed" as const,
  source: "original" as const,
  authorId: "author.mehta",
  reviewerId: "reviewer.alvarez",
  publicationState: "published" as const,
};

function item(p: Omit<Item, keyof typeof BASE> & Partial<Item>): Item {
  return { ...BASE, ...p };
}

export const PRACTICE_ITEMS: Item[] = [
  item({
    id: "p-mcq-slope-meaning",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: ["c-slope-as-rate"],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-slope-read",
    expectedTimeSec: 40,
    prompt: "The slope of a position-time graph is equal to which quantity?",
    choices: [
      { id: "a", text: "Position" },
      { id: "b", text: "Velocity" },
      { id: "c", text: "Acceleration" },
      { id: "d", text: "Elapsed time" },
    ],
    correctChoiceId: "b",
    solution: "By definition v = Δx/Δt, which is the slope of x versus t.",
    hints: ["Slope is a rate of change.", "The dependent variable is position.", "Δx/Δt is velocity."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Identify what x-t slope represents.",
  }),
  item({
    id: "p-mcq-height-not-speed",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-height-slope",
    expectedTimeSec: 55,
    prompt:
      "At the same clock reading, object P is at x = 20 m on a nearly flat x-t graph. Object Q is at x = 2 m on a steep x-t graph. Which object is moving faster?",
    choices: [
      { id: "a", text: "P, because 20 m is a larger position.", misconceptionTag: "mc-height-as-slope" },
      { id: "b", text: "Q, because its graph is steeper." },
      { id: "c", text: "They have equal speed because the time is the same." },
      { id: "d", text: "P, because it has travelled farther from the origin at some earlier time." },
    ],
    correctChoiceId: "b",
    solution: "Faster motion means a steeper |slope| on x-t, not a larger position.",
    hints: ["Height is where the object is.", "Steepness is how fast position is changing.", "Q has the larger |v|."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Compare speed from height versus slope.",
  }),
  item({
    id: "p-mcq-rest-graph",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-xt-shape",
    expectedTimeSec: 40,
    prompt: "Which x-t graph shows an object at rest at x = 5 m?",
    choices: [
      { id: "a", text: "A horizontal line at x = 5 m." },
      { id: "b", text: "A straight line through the origin with slope 5 m/s." },
      { id: "c", text: "A vertical line at t = 5 s." },
      { id: "d", text: "Any graph that reaches 5 m." },
    ],
    correctChoiceId: "a",
    solution: "Rest means v = 0, so slope is zero: a horizontal line. The height of that line is the (unchanging) position.",
    hints: ["Rest means slope zero.", "The position value is the height of that horizontal line.", "A vertical line is not a possible x-t graph for a real object."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Identify the rest graph.",
  }),
  item({
    id: "p-mcq-speeding-up-xt",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-xt-shape",
    expectedTimeSec: 50,
    prompt: "An x-t graph curves upward (slope becoming more positive). The object is:",
    choices: [
      { id: "a", text: "Moving in +x and speeding up." },
      { id: "b", text: "Moving in +x at constant speed." },
      { id: "c", text: "At rest." },
      { id: "d", text: "Moving in −x and slowing down." },
    ],
    correctChoiceId: "a",
    solution: "Increasing positive slope means velocity is becoming more positive: speeding up in the +x direction.",
    hints: ["Watch how steepness changes.", "More positive slope → larger positive velocity.", "That is speeding up in +x."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Interpret a concave-up x-t graph.",
  }),
  item({
    id: "p-rank-steepest",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "ranking",
    difficulty: "standard",
    familyId: "fam-rank-speed",
    expectedTimeSec: 70,
    prompt:
      "Rank the speeds of three carts from greatest to least. All graphs are x versus t. Cart J: slope 4 m/s. Cart K: slope −5 m/s. Cart L: slope 1 m/s.",
    ranking: {
      options: [
        { id: "j", text: "Cart J (slope +4 m/s)" },
        { id: "k", text: "Cart K (slope −5 m/s)" },
        { id: "l", text: "Cart L (slope +1 m/s)" },
      ],
      correctOrder: ["k", "j", "l"],
    },
    solution: "Speed is |v|. |−5| = 5, |4| = 4, |1| = 1, so K > J > L. Direction does not reduce speed.",
    hints: [
      "Speed is the magnitude of velocity.",
      "A negative slope can still mean a large speed.",
      "Order by absolute value of slope.",
    ],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Rank speeds from signed slopes.",
  }),
  item({
    id: "p-num-average-v",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.1",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "foundation",
    familyId: "fam-displacement",
    calculator: "allowed",
    expectedTimeSec: 60,
    prompt:
      "A runner’s position is x = 12 m at t = 2.0 s and x = 28 m at t = 6.0 s. What is the average velocity? Include the unit.",
    numerical: {
      value: 4,
      unit: "m/s",
      tolerance: 0.05,
      acceptedUnits: ["m/s"],
    },
    solution: "v_avg = (28 − 12) m / (6.0 − 2.0) s = 16/4 = 4.0 m/s.",
    hints: ["Average velocity uses displacement, not a single position.", "Δx = 16 m, Δt = 4.0 s.", "16/4 = 4 m/s."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Compute average velocity from two positions.",
  }),
  item({
    id: "p-num-displacement",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.1",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "foundation",
    familyId: "fam-displacement",
    calculator: "allowed",
    expectedTimeSec: 50,
    prompt:
      "A bee flies from x = −3.0 m to x = +5.0 m. What is its displacement? Include the unit and a sign (negative if toward −x).",
    numerical: {
      value: 8,
      unit: "m",
      tolerance: 0.05,
      acceptedUnits: ["m"],
    },
    solution: "Δx = x_f − x_i = 5.0 − (−3.0) = +8.0 m.",
    hints: ["Displacement is final minus initial position.", "Subtracting a negative adds.", "5 − (−3) = 8 m."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Compute displacement including sign.",
  }),
  item({
    id: "p-mcq-negative-v",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-sign",
    expectedTimeSec: 45,
    prompt: "A negative velocity means the object is:",
    choices: [
      { id: "a", text: "Slowing down." },
      { id: "b", text: "Moving in the negative direction." },
      { id: "c", text: "At a negative position." },
      { id: "d", text: "Impossible; speed cannot be negative." },
    ],
    correctChoiceId: "b",
    solution:
      "The sign of velocity is direction. Slowing down is about whether speed is decreasing, which involves acceleration. Position can be positive while velocity is negative.",
    hints: ["Sign of v is direction, not “slow.”", "Speed is |v| and is never negative.", "Negative v means motion toward smaller x."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Interpret the sign of velocity.",
  }),
  item({
    id: "p-mcq-vt-accel",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: ["c-slope-as-rate"],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-vt-turn",
    expectedTimeSec: 50,
    prompt: "The slope of a velocity-time graph is equal to which quantity?",
    choices: [
      { id: "a", text: "Position" },
      { id: "b", text: "Velocity" },
      { id: "c", text: "Acceleration" },
      { id: "d", text: "Speed" },
    ],
    correctChoiceId: "c",
    solution: "a = Δv/Δt, which is the slope of v versus t. Do not reuse the x-t rule without checking the axes.",
    hints: ["Always read the vertical axis.", "Rate of change of velocity is acceleration.", "Slope of v-t is a."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Identify what v-t slope represents.",
  }),
  item({
    id: "p-mcq-zero-v-a",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-turning",
    expectedTimeSec: 55,
    prompt: "Which situation can be true at a single instant?",
    choices: [
      { id: "a", text: "v = 0 and a ≠ 0" },
      { id: "b", text: "The object has a position, so it cannot have a velocity." },
      { id: "c", text: "v ≠ 0 is required whenever a ≠ 0" },
      { id: "d", text: "If v = 0 then the object must remain at rest afterwards." },
    ],
    correctChoiceId: "a",
    solution: "Velocity and acceleration are independent at an instant. A turning point has v = 0 with a ≠ 0.",
    hints: ["Think of the top of a toss.", "Zero can be a value that is still changing.", "v = 0 and a ≠ 0 is allowed."],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Allow zero velocity with nonzero acceleration.",
  }),
  item({
    id: "p-num-accel",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.3",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "standard",
    familyId: "fam-algebra",
    calculator: "allowed",
    expectedTimeSec: 60,
    prompt:
      "A ball’s velocity changes from +8.0 m/s to 0 in 0.80 s. What is the average acceleration? Include the unit (use a negative sign if a is in the −x direction).",
    numerical: {
      value: -10,
      unit: "m/s^2",
      tolerance: 0.15,
      acceptedUnits: ["m/s^2", "m/s²", "m s^-2"],
    },
    solution: "a_avg = (0 − 8.0) / 0.80 = −10 m/s².",
    hints: ["a = Δv/Δt.", "Δv is negative.", "−8.0 / 0.80 = −10 m/s²."],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Compute average acceleration while slowing to rest.",
  }),
  item({
    id: "p-mcq-tangent",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-slope-read",
    expectedTimeSec: 50,
    prompt: "For a curved x-t graph, instantaneous velocity at time t is:",
    choices: [
      { id: "a", text: "The height of the graph at t." },
      { id: "b", text: "The slope of the tangent to the graph at t." },
      { id: "c", text: "The area under the graph from 0 to t." },
      { id: "d", text: "Always zero because a curve means the object is confused." },
    ],
    correctChoiceId: "b",
    solution: "Instantaneous velocity is the derivative dx/dt, read as the tangent slope. Height is still just position.",
    hints: ["Instantaneous rate uses a tangent.", "Do not use the height.", "Tangent slope at t is v(t)."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Define instantaneous velocity on a curve.",
  }),
  item({
    id: "p-exp-not-height",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "explanation",
    difficulty: "standard",
    familyId: "fam-explain-slope",
    expectedTimeSec: 100,
    prompt:
      "A student says “cart A is above cart B on the x-t graph, so A is faster.” Write a correction that a classmate could use.",
    explanationRubric: [
      {
        id: "r1",
        points: 1,
        criterion: "States that graph height is position, not speed.",
        evidenceHint: "Height / position vs speed.",
      },
      {
        id: "r2",
        points: 1,
        criterion: "States that speed is determined from slope or steepness.",
        evidenceHint: "Slope / steep / Δx/Δt.",
      },
    ],
    solution: "Being higher means a larger position, not a larger speed. Compare the slopes at the same time.",
    hints: ["Name what height represents.", "Name what slope represents.", "Faster = steeper, not higher."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Written correction of height-as-speed.",
  }),
  item({
    id: "p-mcq-same-x-diff-v",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-height-slope",
    expectedTimeSec: 50,
    prompt: "Two carts pass the same position at the same time. Can they have different velocities?",
    choices: [
      { id: "a", text: "No. Same position at the same time means the same velocity." },
      { id: "b", text: "Yes. Position does not determine velocity; the rates of change can differ." },
      { id: "c", text: "Only if one cart has a larger mass." },
      { id: "d", text: "Only if they started from different origins." },
    ],
    correctChoiceId: "b",
    solution: "x(t) matching at one instant does not constrain dx/dt. Their graphs can cross with different slopes.",
    hints: ["Crossing graphs can have different steepness.", "Position is not velocity.", "Yes, they can."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Crossing trajectories with different slopes.",
  }),
  item({
    id: "p-mcq-direction-change",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: ["c-zero-v-nonzero-a"],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-xt-shape",
    expectedTimeSec: 55,
    prompt: "An x-t graph reaches a peak and then decreases. At the peak:",
    choices: [
      { id: "a", text: "The object’s velocity is instantaneously zero." },
      { id: "b", text: "The object’s acceleration must be zero." },
      { id: "c", text: "The object has left the axis system." },
      { id: "d", text: "Position is zero." },
    ],
    correctChoiceId: "a",
    solution:
      "At a smooth peak the tangent is horizontal, so v = 0 for an instant. Acceleration is not determined to be zero from that fact alone.",
    hints: ["A peak has a horizontal tangent.", "Horizontal tangent on x-t means v = 0.", "That does not force a = 0."],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Interpret a peak on an x-t graph.",
  }),
  item({
    id: "p-mcq-units-a",
    unitId: "foundation",
    topicId: "f-algebra",
    objectiveId: "F.A.1",
    primaryConceptId: "c-slope-as-rate",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-units",
    expectedTimeSec: 35,
    prompt: "Which unit belongs to acceleration?",
    choices: [
      { id: "a", text: "m/s" },
      { id: "b", text: "m/s²" },
      { id: "c", text: "m" },
      { id: "d", text: "s²" },
    ],
    correctChoiceId: "b",
    solution: "a = Δv/Δt so units are (m/s)/s = m/s².",
    hints: ["Start from units of velocity.", "Divide by seconds again.", "m/s²."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Units of acceleration.",
  }),
  item({
    id: "p-mcq-stop-not-a0",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-turning",
    expectedTimeSec: 50,
    prompt: "A student argues: “The ball stops at the top, so nothing is happening, so a = 0.” The error is:",
    choices: [
      { id: "a", text: "Confusing the value of velocity with the rate of change of velocity." },
      { id: "b", text: "Using the wrong value of g." },
      { id: "c", text: "Forgetting that mass is zero at the top." },
      { id: "d", text: "There is no error; the student is correct." },
    ],
    correctChoiceId: "a",
    solution: "“Stops” describes v = 0. Acceleration describes how v is changing. Gravity still changes the velocity through zero.",
    hints: ["Separate v from a.", "“Nothing happening” is the tell.", "The misconception is stop ⇒ a = 0."],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Diagnose the stop-means-a-zero argument.",
  }),
  item({
    id: "p-mcq-frame",
    unitId: "u1",
    topicId: "u1-frames",
    objectiveId: "1.K.5",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-frames",
    expectedTimeSec: 55,
    prompt:
      "A person on a train walks toward the front at 1 m/s relative to the train. The train moves at 10 m/s relative to the ground in the same direction. The walker’s velocity relative to the ground is closest to:",
    choices: [
      { id: "a", text: "9 m/s" },
      { id: "b", text: "10 m/s" },
      { id: "c", text: "11 m/s" },
      { id: "d", text: "1 m/s" },
    ],
    correctChoiceId: "c",
    solution: "In 1D with the same direction, v_walker,ground = v_walker,train + v_train,ground = 1 + 10 = 11 m/s.",
    hints: ["Name the two frames.", "Same direction: add the velocities.", "1 + 10 = 11 m/s."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Simple 1D relative velocity.",
  }),
  item({
    id: "p-num-from-graph",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "numerical",
    difficulty: "standard",
    familyId: "fam-slope-read",
    calculator: "allowed",
    expectedTimeSec: 70,
    prompt:
      "Read the graph: the cart goes from x = 0 at t = 0 to x = 6.0 m at t = 3.0 s on a straight line. What is the velocity? Include the unit.",
    stimulus: {
      kind: "position-time",
      caption: "Straight line used for a numerical read.",
      alt: "Line from origin to 6 m at 3 s.",
      points: [
        { t: 0, x: 0 },
        { t: 3, x: 6 },
      ],
      showSlope: true,
    },
    numerical: {
      value: 2,
      unit: "m/s",
      tolerance: 0.05,
      acceptedUnits: ["m/s"],
    },
    solution: "v = 6.0 m / 3.0 s = 2.0 m/s.",
    hints: ["Use the two endpoints.", "Do not report 6 m as the answer.", "2 m/s."],
    misconceptionTags: ["mc-height-as-slope"],
    exposurePool: "practice",
    accessibilityDescription: "Read velocity from a labelled x-t line.",
  }),
  item({
    id: "p-mcq-area-hint",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.3",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-vt-area",
    expectedTimeSec: 50,
    prompt: "On a v-t graph, the area between the curve and the time axis over an interval equals:",
    choices: [
      { id: "a", text: "Acceleration" },
      { id: "b", text: "Displacement during that interval" },
      { id: "c", text: "Average speed with no sign" },
      { id: "d", text: "The object’s mass" },
    ],
    correctChoiceId: "b",
    solution: "Because Δx = v Δt for constant v, and more generally the integral of v dt, the signed area is displacement.",
    hints: ["Area has units (m/s)×s = m.", "Signed metres over an interval is displacement.", "Not acceleration."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Identify area under a v-t graph.",
  }),
  item({
    id: "p-rank-direction",
    unitId: "u1",
    topicId: "u1-graphs",
    objectiveId: "1.K.2",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "representations",
    type: "ranking",
    difficulty: "standard",
    familyId: "fam-rank-speed",
    expectedTimeSec: 80,
    prompt:
      "Rank the x-velocities from most positive to most negative. P: slope +2 m/s. Q: slope 0. R: slope −3 m/s.",
    ranking: {
      options: [
        { id: "p", text: "P: +2 m/s" },
        { id: "q", text: "Q: 0" },
        { id: "r", text: "R: −3 m/s" },
      ],
      correctOrder: ["p", "q", "r"],
    },
    solution: "Most positive is +2, then 0, then −3. This ranking uses signed velocity, not speed.",
    hints: ["Use signed values, not absolute values.", "+2 is greater than 0.", "0 is greater than −3."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Rank signed velocities.",
  }),
  item({
    id: "p-mcq-const-a-toss",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "standard",
    familyId: "fam-turning",
    expectedTimeSec: 45,
    prompt: "While a tossed ball is in the air (neglect air resistance), acceleration is:",
    choices: [
      { id: "a", text: "Zero at the top and g downward elsewhere." },
      { id: "b", text: "g downward the entire time, including the top." },
      { id: "c", text: "g upward on the way up and g downward on the way down." },
      { id: "d", text: "Equal to velocity at every instant." },
    ],
    correctChoiceId: "b",
    solution: "With gravity as the only interaction, acceleration is constant and downward for the whole flight.",
    hints: ["What interaction is present throughout?", "It does not switch off at the peak.", "a is g down the whole time."],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Acceleration during free fall including the peak.",
  }),
  item({
    id: "p-exp-system",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "explanation",
    difficulty: "standard",
    familyId: "fam-explain-turn",
    expectedTimeSec: 110,
    prompt:
      "In the tossed-ball problem, identify the system and the principle you use to decide whether a is zero at the top. One or two sentences.",
    explanationRubric: [
      {
        id: "r1",
        points: 1,
        criterion: "Identifies the system as the ball (or ball + Earth for gravity).",
        evidenceHint: "Names the ball as the system.",
      },
      {
        id: "r2",
        points: 1,
        criterion: "Uses that gravity still acts / acceleration is the rate of change of velocity, so a is not zero.",
        evidenceHint: "Gravity or dv/dt still nonzero.",
      },
    ],
    solution:
      "System: the ball. Principle: acceleration is caused by the net interaction; gravity still acts at the top, so a is not zero even though v is.",
    hints: ["Start with “System: …”", "Name the remaining interaction.", "a = dv/dt, not “whether it looks stopped.”"],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Identify system and principle at the peak.",
  }),
  item({
    id: "p-mcq-calc-ok",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.3",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "mathematical",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-units",
    expectedTimeSec: 40,
    prompt: "On the May 2027 AP Physics 1 exam, calculators are:",
    choices: [
      { id: "a", text: "Forbidden on both sections." },
      { id: "b", text: "Allowed on both sections." },
      { id: "c", text: "Allowed only on free-response." },
      { id: "d", text: "Allowed only on multiple choice." },
    ],
    correctChoiceId: "b",
    solution: "The 2027 format allows calculators on both the multiple-choice and free-response sections.",
    hints: ["This is an exam-format fact, not a physics derivation.", "Both sections allow calculators.", "Choose “both sections.”"],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Exam format: calculator policy.",
  }),
  item({
    id: "p-transfer-incline",
    unitId: "u1",
    topicId: "u1-vectors",
    objectiveId: "1.K.4",
    primaryConceptId: "c-zero-v-nonzero-a",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "transfer",
    familyId: "fam-turning-transfer",
    expectedTimeSec: 70,
    prompt:
      "You push a cart up a ramp and release it. It travels up, stops for an instant, and comes down. At the highest point on the ramp, the cart’s acceleration along the ramp is:",
    choices: [
      { id: "a", text: "Zero, because the cart stopped." },
      { id: "b", text: "Nonzero and down the ramp." },
      { id: "c", text: "Nonzero and up the ramp, leftover from the push." },
      { id: "d", text: "Infinite, because direction changes." },
    ],
    correctChoiceId: "b",
    solution:
      "After release, the along-ramp component of gravity (and possibly friction) still points down the ramp, so acceleration is down the ramp at the turning point.",
    hints: ["The push has ended.", "What still acts along the ramp?", "a is down the ramp, v is zero."],
    misconceptionTags: ["mc-stop-means-a-zero"],
    exposurePool: "practice",
    accessibilityDescription: "Transfer turning-point idea to a ramp.",
  }),
  item({
    id: "p-mcq-ref-zero",
    unitId: "u1",
    topicId: "u1-frames",
    objectiveId: "1.K.1",
    primaryConceptId: "c-xt-velocity",
    secondaryConceptIds: [],
    sciencePractice: "conceptual",
    type: "mcq",
    difficulty: "foundation",
    familyId: "fam-frames",
    expectedTimeSec: 40,
    prompt: "Changing the origin of the x-axis (a new zero of position) changes:",
    choices: [
      { id: "a", text: "Displacement between two events." },
      { id: "b", text: "The numerical values of positions, but not displacements." },
      { id: "c", text: "The laws of physics." },
      { id: "d", text: "The sign of time." },
    ],
    correctChoiceId: "b",
    solution: "Positions are origin-dependent. Differences Δx are not. Velocity, which uses Δx, is unchanged by a shifted origin.",
    hints: ["Position readings depend on where you put zero.", "Differences cancel the shift.", "Displacement is unchanged."],
    misconceptionTags: [],
    exposurePool: "practice",
    accessibilityDescription: "Effect of shifting the origin.",
  }),
];
